import { ref } from 'vue'
import type { Attendance } from '@/types/attendance'

export function useAttendance() {
  const attendances = ref<Attendance[]>([])

  const fetchAttendances = async () => {
    attendances.value = [
      // ダミーデータ
      {
        employeeId: '0001',
        name: 'ユーザー01',
        workDays: 20,
        scheduledDays: 22,
        totalHours: '144:00',
        overtimeHours: '12:00',
        lateHours: '2:00',
        lateTime: '0:30',
        earlyLeaveTime: '0:00',
        status: '申請中',
        department: '営業部',
      },
      {
        employeeId: '0002',
        name: 'ユーザー02',
        workDays: 21,
        scheduledDays: 22,
        totalHours: '151:00',
        overtimeHours: '10:00',
        lateHours: '0:00',
        lateTime: '0:00',
        earlyLeaveTime: '0:00',
        status: '承認済み',
        department: '営業部',
      },
      {
        employeeId: '0003',
        name: 'ユーザー03',
        workDays: 19,
        scheduledDays: 22,
        totalHours: '140:00',
        overtimeHours: '5:30',
        lateHours: '1:00',
        lateTime: '0:15',
        earlyLeaveTime: '0:30',
        status: '差戻し',
        department: '人事部',
      },
      {
        employeeId: '0004',
        name: 'ユーザー04',
        workDays: 22,
        scheduledDays: 22,
        totalHours: '160:00',
        overtimeHours: '8:00',
        lateHours: '0:00',
        lateTime: '0:00',
        earlyLeaveTime: '0:00',
        status: '申請中',
        department: '総務部',
      },
      {
        employeeId: '0005',
        name: 'ユーザー05',
        workDays: 18,
        scheduledDays: 22,
        totalHours: '132:00',
        overtimeHours: '0:00',
        lateHours: '3:00',
        lateTime: '0:45',
        earlyLeaveTime: '1:00',
        status: '否認',
        department: '営業部',
      },
      {
        employeeId: '0006',
        name: 'ユーザー06',
        workDays: 20,
        scheduledDays: 22,
        totalHours: '145:00',
        overtimeHours: '6:00',
        lateHours: '0:30',
        lateTime: '0:10',
        earlyLeaveTime: '0:00',
        status: '承認済み',
        department: '開発部',
      },
      {
        employeeId: '0007',
        name: 'ユーザー07',
        workDays: 22,
        scheduledDays: 22,
        totalHours: '160:00',
        overtimeHours: '12:00',
        lateHours: '0:00',
        lateTime: '0:00',
        earlyLeaveTime: '0:00',
        status: '申請中',
        department: '開発部',
      },
      {
        employeeId: '0008',
        name: 'ユーザー08',
        workDays: 17,
        scheduledDays: 22,
        totalHours: '128:00',
        overtimeHours: '4:00',
        lateHours: '2:30',
        lateTime: '0:20',
        earlyLeaveTime: '0:30',
        status: '差戻し',
        department: '人事部',
      },
      {
        employeeId: '0009',
        name: 'ユーザー09',
        workDays: 21,
        scheduledDays: 22,
        totalHours: '152:00',
        overtimeHours: '10:00',
        lateHours: '0:00',
        lateTime: '0:00',
        earlyLeaveTime: '0:00',
        status: '承認済み',
        department: '営業部',
      },
      {
        employeeId: '0010',
        name: 'ユーザー10',
        workDays: 20,
        scheduledDays: 22,
        totalHours: '144:00',
        overtimeHours: '7:00',
        lateHours: '1:30',
        lateTime: '0:25',
        earlyLeaveTime: '0:15',
        status: '申請中',
        department: '総務部',
      }
  ]}

  return {
    attendances,
    fetchAttendances,
  }
}