import { ref } from 'vue'
import type { HrRecord } from '@/types/hr'

const hrRecords = ref<HrRecord[]>([
  {
    employeeId: 'HR001',
    employeeCode: '001',
    lastName: '田中',
    firstName: '太郎',
    lastNameKana: 'タナカ',
    firstNameKana: 'タロウ',
    fullNameNote: '',
    gender: '男性',
    birthDate: '1990-01-01',
    department: '営業部',
    employmentType: '正社員',
    workStatus: '在籍中',
    hireDate: '2020-04-01',
    retireDate: '',
    phoneType: '携帯',
    phoneNumber: '090-1234-5678',
    faxNumber: '',
    email: 'tanaka@example.com',
    addressType: '現住所',
    zip: '1000001',
    prefecture: '東京都',
    city: '千代田区',
    cityKana: 'チヨダク',
    address1: '丸の内1-1',
    address2: '',
    address1Kana: 'マルノウチ',
    address2Kana: '',
    approvalStatus: '承認済み',
  },
  {
    employeeId: 'HR002',
    employeeCode: '002',
    lastName: '鈴木',
    firstName: '一郎',
    lastNameKana: 'スズキ',
    firstNameKana: 'イチロウ',
    fullNameNote: '',
    gender: '男性',
    birthDate: '1990-01-01',
    department: '経理部',
    employmentType: '正社員',
    workStatus: '在籍中',
    hireDate: '2020-04-01',
    retireDate: '',
    phoneType: '携帯',
    phoneNumber: '090-2345-6789',
    faxNumber: '',
    email: 'suzuki@example.com',
    addressType: '現住所',
    zip: '1000001',
    prefecture: '東京都',
    city: '千代田区',
    cityKana: 'チヨダク',
    address1: '丸の内1-1',
    address2: '',
    address1Kana: 'マルノウチ',
    address2Kana: '',
    approvalStatus: '申請中',
  },
  {
    employeeId: 'HR003',
    employeeCode: '003',
    lastName: '山田',
    firstName: '花子',
    lastNameKana: 'ヤマダ',
    firstNameKana: 'ハナコ',
    fullNameNote: '',
    gender: '女性',
    birthDate: '1990-01-01',
    department: '開発部',
    employmentType: '正社員',
    workStatus: '休職中',
    hireDate: '2020-04-01',
    retireDate: '',
    phoneType: '携帯',
    phoneNumber: '090-2345-6789',
    faxNumber: '',
    email: 'suzuki@example.com',
    addressType: '現住所',
    zip: '1000001',
    prefecture: '東京都',
    city: '千代田区',
    cityKana: 'チヨダク',
    address1: '丸の内1-1',
    address2: '',
    address1Kana: 'マルノウチ',
    address2Kana: '',
    approvalStatus: '差戻し',
  },
  {
    employeeId: 'HR004',
    employeeCode: '004',
    lastName: '中村',
    firstName: '杏奈',
    lastNameKana: 'ナカムラ',
    firstNameKana: 'アンナ',
    fullNameNote: '',
    gender: '女性',
    birthDate: '1990-01-01',
    department: '開発部',
    employmentType: '正社員',
    workStatus: '休職中',
    hireDate: '2020-04-01',
    retireDate: '',
    phoneType: '携帯',
    phoneNumber: '090-2345-6789',
    faxNumber: '',
    email: 'suzuki@example.com',
    addressType: '現住所',
    zip: '1000001',
    prefecture: '東京都',
    city: '千代田区',
    cityKana: 'チヨダク',
    address1: '丸の内1-1',
    address2: '',
    address1Kana: 'マルノウチ',
    address2Kana: '',
    approvalStatus: '申請中',
  },
])

export function useHrRecords() {
  return { hrRecords }
}